#pragma once
#include <cstdint>     // uint8_t
#include "I2cBus.hpp"
#include "main.h"      // HAL handles (hi2c1) and HAL_I2C_* functions

/*
 * I2cBusHal — concrete implementation of I2cBus that
 * forwards every call to the STM32 HAL I²C driver, using
 * the global handle ‘hi2c1’ generated by CubeMX.
 */
class I2cBusHal : public I2cBus
{
public:
    bool writeByte(uint8_t device7bitAddress,
                   uint8_t registerAddress,
                   uint8_t value) override;

    bool readBytes(uint8_t  device7bitAddress,
                   uint8_t  startRegister,
                   uint8_t* buffer,
                   uint8_t  length) override;
};
